"""transaction flag_details

Revision ID: 4079738667dd
Revises: cd6979a3974b
Create Date: 2026-07-26 16:24:49.920315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4079738667dd'
down_revision = 'cd6979a3974b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_details', sa.JSON(), nullable=False, server_default='[]'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('flag_details')

    # ### end Alembic commands ###
