"""custom roles org scoping

Revision ID: cd6979a3974b
Revises: c53ac68ba2e9
Create Date: 2026-07-24 17:19:12.858878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'cd6979a3974b'
down_revision = 'c53ac68ba2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_role_organization_id_organization'), 'organization', ['organization_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_role_organization_id_organization'), type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
